name: Cypress Tests using Cypress Docker Image

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    container: 
      image: cypress/included:cypress-12.8.1-node-18.14.1-chrome-111.0.5563.64-1-ff-111.0-edge-111.0.1661.43-1
      options: --user root
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3

      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v5.5.1 # use the explicit version number
        with:
          # Specify Browser since container image is compile with Firefox
          browser: firefox
